### ISSUE TITLE
Rotary encoder?

### ISSUE THREAD

**Issue by Budman1758** [enesbcs/mpyeasy-async#2]
I see the rotary encoder.py file in the src folder of the code but it does not show up in the device list when trying to add one. Is it possible to set one up? I would like to enable 2 of them.

**Comment by enesbcs** [comment]
The src contained Rotary encoder plugin from threading mpyeasy, and it is not working.. i modified to use polling method instead interrupts and it seems to work finally with asyncio. Next version will contain that.

**Comment by enesbcs** [comment]
Added at commit https://github.com/enesbcs/mpyeasy-async/commit/e90610b2690b4a0af9025bf4c15391c0365d89ef
