### ISSUE TITLE
Unit number always reverts back to "0"

### ISSUE THREAD

**Issue by Budman1758** [enesbcs/mpyeasy-async#4]
I have ESPEasy P2P controller in use and that seems to work fine. After a reboot the unit number I assign always reverts back to zero.

**Comment by enesbcs** [comment]
Thanks for testing it has to be a settings loading error.

**Comment by Budman1758** [comment]
Another thing I notice is on the main page where the node list is it shows all other nodes that I have but the unit itself does not show in it like it does in RPIEasy or ESPEasy units. Probably not a big deal but thought I would mention it.

**Comment by enesbcs** [comment]
Yes mpyeasy and mpyeasy-async sends broadcast UDP messages to each node, but it seems, that it never gets back its own packages, so nodes did not show on its own listing... although it is not impossible to add some extra code to show itself on the node list.

**Comment by enesbcs** [comment]
Unit number saving fixed in commit https://github.com/enesbcs/mpyeasy-async/commit/e90610b2690b4a0af9025bf4c15391c0365d89ef

**Comment by Budman1758** [comment]
Saving unit number is working now. Don't know if you added the code to show itself on the main page or not but that does not work yet. If not worried about that (I'm not) then feel free to close this one.
