### ISSUE TITLE
OLED plugins non-functional.

### ISSUE THREAD

**Issue by Budman1758** [enesbcs/mpyeasy-async#9]
Have tried to use both types of OLED plugins and nothing works. I2C scan shows them connected. In the device overview page it always shows -1 for gpio.  See attached screenshot.

![image](https://user-images.githubusercontent.com/6570134/194164145-7e9b0e2b-603f-4b34-9c3b-6040dff3cd7c.png)

**Comment by enesbcs** [comment]
Tested and works after commit https://github.com/enesbcs/mpyeasy-async/commit/e90610b2690b4a0af9025bf4c15391c0365d89ef
